Repository Externalizable/bongo.cat, pull requests merged in 2020-11, with the labels that each got.

#151 Catalan translation
  index.html
  js/core.js
Labels: Priority: High, Status: In Progress, Type: Enhancement

#170 Ode to Joy melody is misattributed #168
  README.md
Labels: Priority: Low, Status: In Progress, Type: Bug

#154 Add link on README.md image to https://bongo.cat
  README.md
Labels: Priority: Low, Status: In Progress, Type: Enhancement
